import { company, LegalPage, Section } from "../components/LegalPage";

export default function Page(){return <LegalPage title="Politique de confidentialité" intro="Cette politique décrit les traitements de données réalisés par JEANECO dans le cadre du service LEXIA.">
<Section title="1. Responsable du traitement"><p><strong>{company.name}</strong>, {company.form}, siège social {company.address}, est responsable du traitement. Contact vie privée : <a href={`mailto:${company.email}`}>{company.email}</a>.</p></Section>
<Section title="2. Données traitées"><ul><li>identité, coordonnées et informations professionnelles ;</li><li>données de compte et de connexion ;</li><li>faits, messages, objectifs, parties concernées et statut des dossiers ;</li><li>documents et pièces transmis ;</li><li>données de facturation et références de paiement ;</li><li>journaux techniques, adresse IP, appareil et éléments de sécurité.</li></ul><p>Les dossiers peuvent contenir des données sensibles. L’utilisateur doit limiter ses transmissions aux informations nécessaires.</p></Section>
<Section title="3. Finalités et bases légales"><ul><li>création du compte et traitement du dossier : exécution du contrat ou mesures précontractuelles ;</li><li>paiement, facturation et comptabilité : contrat et obligations légales ;</li><li>sécurité, prévention des abus et preuve : intérêt légitime et obligations légales ;</li><li>prospection et cookies non essentiels : consentement lorsqu’il est requis.</li></ul></Section>
<Section title="4. Destinataires"><p>Les données sont accessibles aux personnes habilitées de JEANECO, aux juristes ou professionnels affectés, aux avocats lorsque l’orientation est demandée ou acceptée, et aux prestataires techniques nécessaires : Supabase, Vercel, Stripe, Resend et OVHcloud. Elles peuvent être communiquées aux autorités lorsque la loi l’exige.</p></Section>
<Section title="5. Transferts internationaux"><p>Certains prestataires peuvent traiter des données hors de l’Espace économique européen. JEANECO s’appuie alors sur un mécanisme reconnu par le RGPD, notamment une décision d’adéquation ou des clauses contractuelles types.</p></Section>
<Section title="6. Conservation"><ul><li>comptes : durée de la relation, puis archivage limité ;</li><li>dossiers et échanges : durée nécessaire à la prestation puis aux obligations de preuve ;</li><li>factures et pièces comptables : durée légale ;</li><li>journaux de sécurité : durée proportionnée à la prévention des incidents ;</li><li>prospection : jusqu’au retrait du consentement ou à l’expiration de la durée applicable.</li></ul></Section>
<Section title="7. Vos droits"><p>Vous pouvez demander l’accès, la rectification, l’effacement, la limitation, l’opposition, la portabilité et retirer votre consentement. Écrivez à <a href={`mailto:${company.email}`}>{company.email}</a>. Une preuve d’identité peut être demandée en cas de doute raisonnable. Vous pouvez aussi saisir la CNIL.</p></Section>
<Section title="8. Sécurité"><p>LEXIA applique des contrôles d’accès, une authentification, le chiffrement des communications, une journalisation, des sauvegardes et une séparation des rôles. Aucun système n’étant totalement invulnérable, l’utilisateur doit protéger son mot de passe et signaler toute activité suspecte.</p></Section>
<Section title="9. Cookies"><p>Les cookies nécessaires à l’authentification, à la sécurité et au fonctionnement peuvent être déposés sans consentement. Les cookies non essentiels ne sont activés qu’après choix de l’utilisateur. Voir la page <a href="/cookies">Cookies</a>.</p></Section>
<Section title="10. Mise à jour"><p>Cette politique peut évoluer selon le service, les prestataires ou la réglementation. La version publiée sur le site est la version applicable.</p></Section>
</LegalPage>}
