"use client";
import Link from "next/link";
import {useState} from "react";
import AmiableLetterStudio from "../AmiableLetterStudio";
import "../../admin.css";

export default function CourriersPage(){
 const [reference,setReference]=useState(""); const [client,setClient]=useState(""); const [subject,setSubject]=useState(""); const [objective,setObjective]=useState("");
 return <main className="admin-app"><section className="admin-main" style={{maxWidth:1050,margin:"0 auto",padding:"28px 18px 100px"}}><Link href="/administration/mes-dossiers" style={{fontWeight:800,color:"#0c2340"}}>← Retour aux dossiers</Link><header style={{margin:"24px 0"}}><small style={{fontWeight:900,color:"#9a7a39",letterSpacing:1}}>OUTIL ÉQUIPE JURIDIQUE</small><h1 style={{color:"#0c2340",margin:"7px 0"}}>Courriers & résolution amiable</h1><p style={{color:"#667085",maxWidth:720}}>Préparez une correspondance LEXIA à partir des informations du dossier. Le document reste sous le contrôle du juriste avant tout envoi.</p></header><section style={{padding:18,border:"1px solid #e8e1d5",borderRadius:16,background:"white",display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}><label style={{display:"grid",gap:6,fontSize:11,fontWeight:800}}>Référence dossier<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="LEX-2026-..." style={{padding:11,border:"1px solid #d9d3c8",borderRadius:10}}/></label><label style={{display:"grid",gap:6,fontSize:11,fontWeight:800}}>Partie requérante<input value={client} onChange={e=>setClient(e.target.value)} placeholder="Nom du client" style={{padding:11,border:"1px solid #d9d3c8",borderRadius:10}}/></label><label style={{display:"grid",gap:6,fontSize:11,fontWeight:800}}>Objet du dossier<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Objet du litige" style={{padding:11,border:"1px solid #d9d3c8",borderRadius:10}}/></label><label style={{display:"grid",gap:6,fontSize:11,fontWeight:800}}>Solution recherchée<input value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Résultat souhaité" style={{padding:11,border:"1px solid #d9d3c8",borderRadius:10}}/></label></section>{reference&&client&&subject?<AmiableLetterStudio reference={reference} clientName={client} subject={subject} objective={objective||null}/>:<div style={{marginTop:18,padding:18,borderRadius:14,background:"#f8f5ef",color:"#667085"}}>Renseignez la référence, la partie requérante et l’objet du dossier pour ouvrir le studio de courriers.</div>}</section></main>;
}