"use client";

import Link from "next/link";
import { ChangeEvent, FormEvent, useMemo, useState } from "react";
import "./nouveau-dossier.css";

type Urgency = "normale" | "rapide" | "urgente";
type FormState = { category:string; subject:string; description:string; objective:string; urgency:Urgency; adverseKnown:boolean; adverseType:string; adverseName:string; adverseEmail:string; adversePhone:string };

const categories=[
 {icon:"⌂",value:"logement",label:"Logement",detail:"Bail, propriétaire, travaux, dépôt de garantie"},
 {icon:"◫",value:"travail",label:"Travail",detail:"Contrat, salaire, sanction, licenciement"},
 {icon:"◎",value:"consommation",label:"Consommation",detail:"Achat, remboursement, prestation contestée"},
 {icon:"◇",value:"assurance",label:"Assurance",detail:"Sinistre, indemnisation, refus de prise en charge"},
 {icon:"♙",value:"famille",label:"Famille",detail:"Séparation, pension, autorité parentale"},
 {icon:"▦",value:"entreprise",label:"Entreprise",detail:"Contrats, impayés, litiges commerciaux"},
 {icon:"⌖",value:"administration",label:"Administration",detail:"Décision, recours, contestation"},
 {icon:"+",value:"autre",label:"Autre situation",detail:"Décrivez librement votre demande"}
];
const urgencyOptions=[
 {value:"normale" as Urgency,label:"Normal",price:13,detail:"Traitement selon le délai habituel de l'équipe"},
 {value:"rapide" as Urgency,label:"Réponse rapide souhaitée",price:19,detail:"Votre demande est signalée comme prioritaire"},
 {value:"urgente" as Urgency,label:"Urgente",price:23,detail:"Délai, audience ou échéance proche"}
];

export default function NouveauDossierPage(){
 const[step,setStep]=useState(1); const[files,setFiles]=useState<File[]>([]); const[submitted,setSubmitted]=useState(false);
 const[form,setForm]=useState<FormState>({category:"",subject:"",description:"",objective:"",urgency:"normale",adverseKnown:false,adverseType:"particulier",adverseName:"",adverseEmail:"",adversePhone:""});
 const urgency=urgencyOptions.find(x=>x.value===form.urgency)!; const price=urgency.price;
 const selectedCategory=useMemo(()=>categories.find(x=>x.value===form.category),[form.category]);
 function update<K extends keyof FormState>(key:K,value:FormState[K]){setForm(c=>({...c,[key]:value}))}
 function addFiles(e:ChangeEvent<HTMLInputElement>){setFiles(c=>[...c,...Array.from(e.target.files||[])].slice(0,10))}
 function canContinue(){if(step===1)return!!form.category;if(step===2)return form.subject.trim().length>=5&&form.description.trim().length>=40;return true}
 function next(){if(canContinue()){setStep(s=>Math.min(5,s+1));window.scrollTo({top:0,behavior:"smooth"})}}
 function back(){setStep(s=>Math.max(1,s-1));window.scrollTo({top:0,behavior:"smooth"})}
 function submit(e:FormEvent){e.preventDefault();setSubmitted(true);window.scrollTo({top:0,behavior:"smooth"})}
 if(submitted)return <main className="case-success-page"><section className="case-success-card"><div className="case-success-icon">✓</div><span>DEMANDE PRÉPARÉE</span><h1>Votre dossier est prêt à être transmis.</h1><p>Votre niveau de traitement est « {urgency.label} » pour un montant de {price} € TTC. L'étape suivante permettra l'enregistrement et le paiement sécurisé.</p><div className="case-success-actions"><Link href="/tableau-de-bord">Retour à mon espace</Link><button onClick={()=>setSubmitted(false)}>Modifier</button></div></section></main>;
 return <main className="case-page">
  <header className="case-header"><Link href="/" className="case-logo">LEXIA<span>.</span></Link><div className="case-header-actions"><span>Assistance disponible en bas à droite</span><Link href="/tableau-de-bord">Mon espace</Link></div></header>
  <section className="case-layout"><aside className="case-sidebar"><span className="case-sidebar-label">NOUVELLE DEMANDE</span><h1>Déposez votre dossier en quelques étapes.</h1><p>Chaque information nous aide à comprendre votre situation et à vous répondre plus précisément.</p><div className="case-steps">{[[1,"Votre situation"],[2,"Les faits & urgence"],[3,"Partie adverse"],[4,"Documents"],[5,"Récapitulatif"]].map(([n,l])=><div key={n} className={`case-step ${step===n?"active":""} ${step>Number(n)?"done":""}`}><span>{step>Number(n)?"✓":n}</span><div><b>{l}</b><small>Étape {n} sur 5</small></div></div>)}</div><div className="case-price-card"><small>TARIF SÉLECTIONNÉ</small><strong>{price} €</strong><p>{urgency.label}</p></div></aside>
  <section className="case-main"><div className="case-progress"><span style={{width:`${step*20}%`}}/></div><form onSubmit={submit} className="case-form-card">
   {step===1&&<div className="case-section"><span className="case-eyebrow">ÉTAPE 1 · VOTRE SITUATION</span><h2>Quel est le domaine de votre demande ?</h2><p className="case-intro">Sélectionnez la catégorie qui correspond le mieux à votre problème.</p><div className="case-category-grid">{categories.map(c=><button key={c.value} type="button" className={form.category===c.value?"selected":""} onClick={()=>update("category",c.value)}><span>{c.icon}</span><div><b>{c.label}</b><small>{c.detail}</small></div></button>)}</div></div>}
   {step===2&&<div className="case-section"><span className="case-eyebrow">ÉTAPE 2 · LES FAITS & L'URGENCE</span><h2>Expliquez-nous votre situation.</h2><p className="case-intro">Décrivez les faits puis choisissez le niveau de traitement souhaité. Le tarif est affiché immédiatement.</p><label className="case-field">Titre de votre demande<input value={form.subject} onChange={e=>update("subject",e.target.value)} placeholder="Ex. Mon propriétaire refuse de rendre le dépôt de garantie"/></label><label className="case-field">Décrivez votre situation<textarea rows={8} value={form.description} onChange={e=>update("description",e.target.value)} placeholder="Dates importantes, personnes concernées, démarches déjà effectuées…"/><small>{form.description.length} caractères · minimum 40</small></label><label className="case-field">Quel résultat souhaitez-vous obtenir ?<textarea rows={4} value={form.objective} onChange={e=>update("objective",e.target.value)} placeholder="Remboursement, courrier, contestation, mise en demeure…"/></label><div className="urgency-title"><b>Choisissez votre niveau de traitement</b><span>Le prix de votre dossier dépend uniquement de ce choix.</span></div><div className="urgency-grid">{urgencyOptions.map(o=><button type="button" key={o.value} className={form.urgency===o.value?"selected":""} onClick={()=>update("urgency",o.value)}><div><b>{o.label}</b><small>{o.detail}</small></div><strong>{o.price} €</strong>{form.urgency===o.value&&<em>✓ Sélectionné</em>}</button>)}</div></div>}
   {step===3&&<div className="case-section"><span className="case-eyebrow">ÉTAPE 3 · PARTIE ADVERSE</span><h2>Connaissez-vous la partie adverse ?</h2><p className="case-intro">Cette partie reste facultative et pourra être complétée plus tard.</p><div className="case-choice-row"><button type="button" className={form.adverseKnown?"selected":""} onClick={()=>update("adverseKnown",true)}>Oui, je la renseigne</button><button type="button" className={!form.adverseKnown?"selected":""} onClick={()=>update("adverseKnown",false)}>Non, continuer sans</button></div>{form.adverseKnown&&<div className="case-adverse-grid"><label className="case-field">Type<select value={form.adverseType} onChange={e=>update("adverseType",e.target.value)}><option value="particulier">Particulier</option><option value="entreprise">Entreprise</option><option value="administration">Administration</option><option value="avocat">Avocat ou représentant</option></select></label><label className="case-field">Nom ou raison sociale<input value={form.adverseName} onChange={e=>update("adverseName",e.target.value)}/></label><label className="case-field">E-mail<input type="email" value={form.adverseEmail} onChange={e=>update("adverseEmail",e.target.value)}/></label><label className="case-field">Téléphone<input value={form.adversePhone} onChange={e=>update("adversePhone",e.target.value)}/></label></div>}</div>}
   {step===4&&<div className="case-section"><span className="case-eyebrow">ÉTAPE 4 · DOCUMENTS</span><h2>Ajoutez les pièces utiles.</h2><p className="case-intro">Contrats, factures, courriers, captures, photos ou décisions.</p><label className="case-upload-zone"><input type="file" multiple onChange={addFiles} accept=".pdf,.doc,.docx,.jpg,.jpeg,.png"/><span>⇧</span><b>Choisir des fichiers</b><small>PDF, Word, JPG ou PNG · 10 fichiers maximum</small></label><div className="case-file-list">{files.length===0&&<p>Aucun document ajouté.</p>}{files.map((f,i)=><div key={`${f.name}-${i}`}><span>▤</span><div><b>{f.name}</b><small>{Math.max(1,Math.round(f.size/1024))} Ko</small></div><button type="button" onClick={()=>setFiles(x=>x.filter((_,j)=>j!==i))}>Supprimer</button></div>)}</div></div>}
   {step===5&&<div className="case-section"><span className="case-eyebrow">ÉTAPE 5 · RÉCAPITULATIF</span><h2>Vérifiez votre demande.</h2><div className="case-summary-grid"><article><small>DOMAINE</small><b>{selectedCategory?.label||"Non renseigné"}</b><span>{form.category}</span></article><article><small>NIVEAU</small><b>{urgency.label}</b><span>{price} € TTC</span></article><article className="wide"><small>OBJET</small><b>{form.subject}</b><span>{form.description}</span></article><article><small>PARTIE ADVERSE</small><b>{form.adverseKnown?form.adverseName||"À compléter":"Non renseignée"}</b><span>Facultatif</span></article><article><small>DOCUMENTS</small><b>{files.length} fichier{files.length>1?"s":""}</b><span>Ajout possible plus tard</span></article></div><div className="case-payment-summary"><div><small>OUVERTURE DU DOSSIER · {urgency.label.toUpperCase()}</small><b>Analyse initiale et accès à la messagerie</b></div><strong>{price} € TTC</strong></div><label className="case-consent"><input type="checkbox" required/><span>Je confirme l'exactitude des informations transmises et accepte les conditions du service.</span></label></div>}
   <div className="case-navigation"><button type="button" className="case-back" onClick={back} disabled={step===1}>← Précédent</button>{step<5?<button type="button" className="case-next" onClick={next} disabled={!canContinue()}>Continuer →</button>:<button type="submit" className="case-next">Transmettre ma demande →</button>}</div>
  </form></section></section>
 </main>
}
