import Link from "next/link";
import { company, LegalPage, Section } from "../components/LegalPage";

export default function Page(){return <LegalPage title="Conditions générales d’utilisation et de vente" intro="Ces conditions encadrent l’accès à LEXIA, le dépôt d’un dossier et l’achat des prestations proposées par JEANECO.">
<Section title="1. Prestataire"><p>LEXIA est exploité par <strong>{company.name}</strong>, {company.form} au capital de {company.capital}, {company.rcs}, siège social {company.address}. Contact : <a href={`mailto:${company.email}`}>{company.email}</a>.</p></Section>
<Section title="2. Service"><p>LEXIA permet de créer un compte, décrire une situation, transmettre des pièces, échanger avec l’équipe et recevoir une assistance ou une orientation. LEXIA ne remplace pas un avocat et ne garantit aucun résultat.</p></Section>
<Section title="3. Compte"><p>L’utilisateur fournit des informations exactes, protège ses identifiants et signale toute utilisation non autorisée. JEANECO peut suspendre un compte en cas de fraude, abus, contenu illicite ou atteinte à la sécurité.</p></Section>
<Section title="4. Prix et commande"><p>Le prix et les caractéristiques essentielles sont affichés avant paiement. Les offres actuellement présentées comprennent notamment l’ouverture ou l’étude initiale du dossier à 13 € TTC et les prestations complémentaires affichées au moment de la commande. Aucun supplément n’est facturé sans accord exprès.</p><p>La commande est conclue après vérification du récapitulatif, acceptation des présentes conditions et confirmation du paiement.</p></Section>
<Section title="5. Paiement"><p>Les paiements sont sécurisés et traités par Stripe. JEANECO ne conserve pas les données bancaires complètes. En cas d’échec, d’impayé ou de fraude présumée, la prestation peut être suspendue.</p></Section>
<Section title="6. Exécution et disponibilité"><p>Le service est accessible en ligne. La mention 24 h/24 et 7 j/7 concerne l’accès à la plateforme et la possibilité de déposer une demande ; elle ne constitue pas, sauf engagement exprès affiché lors de la commande, une garantie de réponse humaine immédiate.</p></Section>
<Section title="7. Rétractation"><p>Le consommateur dispose en principe de quatorze jours pour se rétracter. Lorsqu’il demande expressément le commencement de la prestation avant l’expiration de ce délai, il peut être redevable du service déjà exécuté. En cas d’exécution complète après accord exprès et renoncement valable, le droit de rétractation peut être perdu.</p><p>La demande peut être adressée à <a href={`mailto:${company.email}`}>{company.email}</a> en indiquant l’identité, l’adresse e-mail du compte et la commande concernée.</p></Section>
<Section title="8. Obligations de l’utilisateur"><ul><li>transmettre uniquement les informations et documents nécessaires et licites ;</li><li>signaler immédiatement toute audience, prescription ou délai ;</li><li>ne pas utiliser le service pour nuire, menacer ou tromper ;</li><li>vérifier les documents avant toute utilisation externe.</li></ul></Section>
<Section title="9. Avocats et professionnels"><p>Toute mise en relation est une orientation. L’acceptation du dossier, les honoraires, les délais et la stratégie relèvent du professionnel indépendant et, le cas échéant, d’une convention distincte.</p></Section>
<Section title="10. Responsabilité"><p>JEANECO exécute le service avec diligence dans son périmètre. L’utilisateur demeure responsable de ses décisions, des informations fournies et du respect de ses délais. Aucune clause n’exclut les responsabilités légalement impératives.</p></Section>
<Section title="11. Données et propriété"><p>Les traitements sont décrits dans la <Link href="/confidentialite">politique de confidentialité</Link>. L’utilisateur conserve ses droits sur ses documents et autorise leur traitement uniquement pour fournir le service.</p></Section>
<Section title="12. Réclamations et litiges"><p>Les réclamations sont adressées à <a href={`mailto:${company.email}`}>{company.email}</a>. Le médiateur de la consommation sera publié dès sa désignation contractuelle. Le droit français s’applique, sous réserve des protections impératives du consommateur.</p></Section>
<Section title="13. Modification"><p>La version applicable est celle acceptée lors de la commande. Toute modification importante est portée à la connaissance des utilisateurs.</p></Section>
</LegalPage>}
