import Link from "next/link";
import "../legal.css";

export default function ConditionsPage() {
  return (
    <main className="legal-page">
      <header className="legal-header"><nav className="legal-nav"><Link href="/" className="legal-logo">LEXIA<span>.</span></Link><div className="legal-nav-links"><Link href="/confidentialite">Confidentialité</Link><Link href="/conditions">Conditions générales</Link><Link href="/mentions-legales">Mentions légales</Link></div></nav></header>

      <section className="legal-hero"><div className="legal-container"><span className="legal-eyebrow">CONDITIONS DU SERVICE</span><h1>Conditions générales d’utilisation et de vente</h1><p>Les présentes conditions encadrent l’accès à la plateforme LEXIA, le dépôt d’une demande et l’achat de prestations d’assistance en ligne.</p><div className="legal-alert">Document de travail à faire valider par un professionnel du droit avant commercialisation. Les informations de société, de médiateur, de paiement et de responsabilité professionnelle restent à compléter.</div></div></section>

      <section className="legal-container legal-content">
        <article className="legal-card"><h2>1. Identité du prestataire</h2><p>Le service LEXIA est édité et exploité par :</p><div className="legal-table"><div className="legal-row"><span>Dénomination sociale</span><span className="legal-placeholder">À compléter avant lancement</span></div><div className="legal-row"><span>Forme et capital</span><span className="legal-placeholder">À compléter avant lancement</span></div><div className="legal-row"><span>RCS / SIREN</span><span className="legal-placeholder">À compléter avant lancement</span></div><div className="legal-row"><span>Siège social</span><span className="legal-placeholder">À compléter avant lancement</span></div><div className="legal-row"><span>Contact</span><span>contact@lexia.fr ou adresse définitive à compléter</span></div></div></article>

        <article className="legal-card"><h2>2. Objet du service</h2><p>LEXIA fournit un espace numérique permettant au client de :</p><ul><li>créer un compte sécurisé ;</li><li>décrire une situation et transmettre des documents ;</li><li>échanger avec l’équipe affectée à sa demande ;</li><li>recevoir des informations générales, des pistes de démarche et une aide à la rédaction ;</li><li>recevoir, le cas échéant, les coordonnées d’un avocat situé à proximité ;</li><li>accepter ou refuser des prestations complémentaires proposées dans la messagerie.</li></ul><p>LEXIA ne remplace pas une consultation d’avocat, ne représente pas le client en justice et ne garantit aucun résultat. Lorsque la situation exige un acte réservé à une profession réglementée, une représentation, un conseil individualisé relevant du monopole d’un avocat ou une intervention urgente, le client est orienté vers un professionnel compétent.</p></article>

        <article className="legal-card"><h2>3. Accès et création de compte</h2><p>L’utilisateur doit fournir des informations exactes, complètes et à jour. Il est responsable de la confidentialité de ses identifiants et de toute activité réalisée depuis son compte.</p><p>LEXIA peut suspendre un compte en cas de fraude, d’usurpation, de comportement abusif, de contenu manifestement illicite, de tentative d’accès non autorisé ou de non-respect des présentes conditions.</p></article>

        <article className="legal-card"><h2>4. Dépôt d’une demande et tarifs</h2><p>Avant validation, le client choisit un niveau de traitement. Les tarifs affichés en euros TTC sont :</p><div className="legal-table"><div className="legal-row"><span>Normal</span><span>13 € TTC</span></div><div className="legal-row"><span>Réponse rapide souhaitée</span><span>19 € TTC</span></div><div className="legal-row"><span>Urgente — délai ou audience proche</span><span>23 € TTC</span></div></div><p>Le niveau d’urgence sert à prioriser la demande mais ne constitue pas une garantie de réponse dans un délai précis tant qu’un délai contractuel ferme n’est pas affiché lors de la commande.</p><p>Pour les clients professionnels, un tarif spécifique pourra être appliqué et sera affiché avant validation. Aucun coût complémentaire ne peut être facturé sans information préalable et accord exprès du client.</p></article>

        <article className="legal-card"><h2>5. Commande et paiement</h2><p>La commande devient définitive après validation du récapitulatif, acceptation des présentes conditions et confirmation du paiement. Une confirmation est adressée sur un support durable.</p><p>Les paiements sont traités par un prestataire de paiement sécurisé dont l’identité sera précisée avant le lancement commercial. LEXIA ne conserve pas les données bancaires complètes.</p><p>En cas de refus de paiement, d’impayé ou de suspicion de fraude, l’accès à la prestation peut être suspendu.</p></article>

        <article className="legal-card"><h2>6. Droit de rétractation</h2><p>Le consommateur dispose en principe d’un délai légal de quatorze jours pour se rétracter d’un contrat conclu à distance.</p><p>Lorsque le client demande expressément que la prestation commence avant la fin de ce délai, il reconnaît qu’en cas d’exécution complète du service avant l’expiration du délai, il peut perdre son droit de rétractation dans les conditions prévues par le Code de la consommation. En cas de commencement d’exécution sans exécution complète, un montant proportionnel au service fourni peut rester dû.</p><p>Une fonctionnalité ou un formulaire de rétractation clairement accessible devra être ajouté avant la commercialisation.</p></article>

        <article className="legal-card"><h2>7. Obligations du client</h2><p>Le client s’engage à :</p><ul><li>transmettre uniquement des informations et documents qu’il est autorisé à communiquer ;</li><li>ne pas masquer volontairement un élément déterminant ;</li><li>signaler immédiatement toute échéance, audience, délai de recours ou mise en demeure ;</li><li>ne pas utiliser la plateforme pour harceler, menacer, diffamer ou organiser une activité illicite ;</li><li>vérifier les courriers, formulations et coordonnées avant toute utilisation ou envoi ;</li><li>consulter sans délai un avocat ou les services d’urgence lorsque la situation le nécessite.</li></ul></article>

        <article className="legal-card"><h2>8. Documents et partie adverse</h2><p>La transmission des coordonnées de la partie adverse est facultative. Le client garantit que les données communiquées sont pertinentes et nécessaires au traitement de sa demande.</p><p>Les documents doivent être lisibles, exempts de logiciel malveillant et ne pas dépasser les limites techniques affichées. LEXIA peut refuser ou supprimer un fichier dangereux, illisible ou manifestement sans rapport avec le dossier.</p></article>

        <article className="legal-card"><h2>9. Prestations complémentaires</h2><p>L’équipe peut proposer, dans la messagerie, une prestation supplémentaire payante, par exemple une rédaction approfondie, l’étude d’un volume important de pièces ou une recherche spécifique. La proposition précise son objet, son prix et, si possible, son délai.</p><p>Le client reste libre de l’accepter ou de la refuser. Aucun travail complémentaire facturable n’est engagé sans accord exprès.</p></article>

        <article className="legal-card"><h2>10. Orientation vers un avocat</h2><p>LEXIA peut communiquer les coordonnées d’un avocat ou d’un cabinet selon la localisation et le domaine concerné. Cette transmission constitue une orientation et non une garantie d’acceptation du dossier, de disponibilité, de tarif ou de résultat.</p><p>La relation entre le client et l’avocat est indépendante de LEXIA, sauf convention contraire clairement indiquée.</p></article>

        <article className="legal-card"><h2>11. Responsabilité</h2><p>LEXIA exécute ses prestations avec diligence, dans le cadre du périmètre annoncé. Le client reste responsable de ses décisions, de l’utilisation des formulations proposées, du respect de ses délais et de la vérification des informations transmises.</p><p>LEXIA ne peut être tenue responsable d’un dommage résultant d’informations incomplètes ou inexactes, d’un délai non signalé, d’une utilisation contraire aux recommandations ou d’une indisponibilité imputable à un tiers, sous réserve des dispositions légales impératives.</p><p>Aucune clause ne limite les responsabilités qui ne peuvent légalement être exclues ou limitées.</p></article>

        <article className="legal-card"><h2>12. Disponibilité et maintenance</h2><p>LEXIA peut interrompre temporairement le service pour maintenance, sécurité ou mise à jour. Les efforts raisonnables sont mis en œuvre pour limiter la durée de l’interruption.</p><p>La plateforme dépend de prestataires techniques, notamment d’hébergement, de base de données et de paiement. Une indisponibilité temporaire ne donne pas automatiquement droit à indemnisation, sauf disposition légale contraire ou engagement spécifique.</p></article>

        <article className="legal-card"><h2>13. Propriété intellectuelle</h2><p>La marque, les textes, interfaces, éléments graphiques, logiciels, bases et contenus propres à LEXIA sont protégés. Toute reproduction ou exploitation non autorisée est interdite.</p><p>Le client conserve ses droits sur ses documents et accorde à LEXIA une autorisation limitée, non exclusive et strictement nécessaire à l’exécution du service.</p></article>

        <article className="legal-card"><h2>14. Données personnelles</h2><p>Les traitements de données sont décrits dans la <Link href="/confidentialite"><strong>politique de confidentialité</strong></Link>, qui fait partie de l’information contractuelle du client.</p></article>

        <article className="legal-card"><h2>15. Réclamations et médiation</h2><p>Toute réclamation doit d’abord être adressée au service client à l’adresse de contact définitive de LEXIA.</p><p>Après réclamation écrite préalable restée sans solution, le consommateur pourra saisir gratuitement le médiateur de la consommation compétent :</p><div className="legal-table"><div className="legal-row"><span>Médiateur</span><span className="legal-placeholder">À désigner avant lancement</span></div><div className="legal-row"><span>Adresse / site</span><span className="legal-placeholder">À compléter avant lancement</span></div></div></article>

        <article className="legal-card"><h2>16. Droit applicable et litiges</h2><p>Les présentes conditions sont soumises au droit français. Le consommateur bénéficie des règles impératives de protection qui lui sont applicables.</p><p>En cas de litige, les parties recherchent d’abord une solution amiable. À défaut, la juridiction compétente est déterminée selon les règles légales applicables, sans imposer au consommateur une clause attributive de compétence illicite.</p></article>

        <article className="legal-card"><h2>17. Modification des conditions</h2><p>LEXIA peut modifier les présentes conditions pour tenir compte d’une évolution légale, technique ou commerciale. La version applicable à une commande est celle acceptée lors de sa validation.</p><p><strong>Dernière mise à jour :</strong> 4 août 2026.</p></article>
      </section>

      <footer className="legal-footer"><div className="legal-footer-inner"><span>LEXIA — Assistance juridique en ligne</span><Link href="/">Retour à l’accueil</Link></div></footer>
    </main>
  );
}
