import { company, LegalPage, Section } from "../components/LegalPage";

export default function Page(){return <LegalPage title="Mentions légales" intro="Informations relatives à l’éditeur, à l’hébergement et au fonctionnement du site lexiafrance.fr.">
<Section title="1. Éditeur"><p>Le site <strong>lexiafrance.fr</strong> et le service LEXIA sont édités par <strong>{company.name}</strong>, {company.form} au capital de {company.capital}, immatriculée sous le numéro {company.rcs}, SIREN {company.siren}, SIRET {company.siret}, TVA intracommunautaire {company.vat}, dont le siège social est situé {company.address}.</p><p>Directeur de la publication et représentant légal : <strong>{company.director}</strong>.<br/>Contact : <a href={`mailto:${company.email}`}>{company.email}</a>.</p></Section>
<Section title="2. Hébergement et prestataires"><p>Le site est hébergé par Vercel Inc., 440 N Barranca Avenue #4133, Covina, CA 91723, États-Unis. Les données applicatives sont traitées via Supabase dans une région européenne. Les paiements sont opérés par Stripe, les e-mails transactionnels par Resend et le nom de domaine est enregistré auprès d’OVHcloud.</p></Section>
<Section title="3. Nature du service"><p>LEXIA fournit un service numérique d’assistance, d’organisation des demandes, d’échange sécurisé et, lorsque nécessaire, de mise en relation avec des professionnels du droit. LEXIA n’est ni un cabinet d’avocats, ni une juridiction, ni un service public.</p><p>Les actes réservés, consultations approfondies, négociations et représentations sont réalisés sous la responsabilité du professionnel habilité concerné, selon ses règles déontologiques et sa propre convention d’honoraires.</p></Section>
<Section title="4. Propriété intellectuelle"><p>Les marques, textes, interfaces, logiciels, bases de données et éléments graphiques sont protégés. Toute reproduction ou exploitation non autorisée est interdite.</p></Section>
<Section title="5. Signalement"><p>Toute demande relative au site, à un contenu, à la sécurité ou aux données personnelles peut être adressée à <a href={`mailto:${company.email}`}>{company.email}</a>.</p></Section>
<Section title="6. Médiation"><p className="legal-note">Le médiateur de la consommation devra être désigné contractuellement par JEANECO avant l’ouverture commerciale au public. Ses coordonnées seront publiées ici dès la désignation effective.</p></Section>
</LegalPage>}
