import type { SeoGuide } from "./seo-guides";

export const extraSeoGuides: SeoGuide[] = [
  {
    slug: "etat-des-lieux-contestation",
    category: "Logement",
    title: "Contester un état des lieux : comment réagir ?",
    description: "Les réflexes à avoir lorsqu'un état des lieux d'entrée ou de sortie ne correspond pas à la réalité du logement.",
    intro: "L'état des lieux joue un rôle important dans les litiges locatifs, notamment pour la restitution du dépôt de garantie et l'imputation d'éventuelles dégradations. Si certaines mentions sont inexactes ou incomplètes, il faut réagir rapidement et conserver des preuves datées.",
    points: [
      { title: "Comparer le document à la réalité", text: "Relisez chaque pièce, équipement et observation. Repérez les éléments absents, imprécis ou manifestement inexacts et rassemblez les photos prises au moment de l'entrée ou de la sortie." },
      { title: "Formuler vos observations par écrit", text: "Évitez de laisser une contestation uniquement orale. Adressez un message ou courrier précis en indiquant les points contestés, les dates et les pièces qui appuient votre position." },
      { title: "Conserver l'ensemble du dossier locatif", text: "Bail, états des lieux, photos, factures, échanges et preuve de remise des clés permettent de replacer la contestation dans son contexte." },
    ],
    checklist: ["Bail de location", "État des lieux contesté", "Photos datées", "Échanges avec le bailleur ou l'agence", "Factures ou justificatifs utiles"],
    faq: [
      { question: "Puis-je contester après avoir signé ?", answer: "Une signature ne rend pas toute contestation impossible, mais les circonstances et les délais comptent. Il est préférable d'agir rapidement et de réunir des preuves objectives." },
      { question: "Les photos sont-elles utiles ?", answer: "Oui, surtout lorsqu'elles sont datées, cohérentes avec les lieux et permettent d'illustrer précisément le point contesté." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "preavis-location-reduire",
    category: "Logement",
    title: "Préavis de location : peut-on le réduire ?",
    description: "Comprendre les situations dans lesquelles un locataire peut bénéficier d'un délai de préavis réduit et les justificatifs à préparer.",
    intro: "La durée du préavis dépend du type de location, de la localisation du logement et parfois de la situation personnelle du locataire. Avant d'envoyer votre congé, vérifiez le délai applicable et les justificatifs nécessaires.",
    points: [
      { title: "Identifier le régime de votre bail", text: "Location vide, meublée, zone tendue ou situation particulière peuvent conduire à des règles différentes. Commencez par relire le bail et identifier précisément votre situation." },
      { title: "Préparer le justificatif adapté", text: "Lorsqu'un préavis réduit dépend d'un événement personnel ou professionnel, joignez le document permettant de l'établir dès l'envoi de votre congé lorsque cela est nécessaire." },
      { title: "Sécuriser la date de départ", text: "La date de réception du congé peut avoir des conséquences sur le calcul du préavis et du loyer restant dû. Gardez une preuve de l'envoi et de la réception." },
    ],
    checklist: ["Contrat de location", "Adresse du logement", "Justificatif du motif invoqué", "Courrier de congé", "Preuve de réception"],
    faq: [
      { question: "Puis-je partir avant la fin du préavis ?", answer: "Vous pouvez quitter matériellement le logement, mais le loyer peut rester dû jusqu'à la fin du préavis sauf situation particulière." },
      { question: "Un e-mail suffit-il ?", answer: "Le mode de notification du congé doit respecter les formes admises. Utilisez un mode qui permet de prouver clairement la réception." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "charges-locatives-contestation",
    category: "Logement",
    title: "Charges locatives trop élevées : comment les contester ?",
    description: "Les documents à demander et les vérifications à effectuer lorsqu'un décompte de charges locatives paraît anormal.",
    intro: "Une régularisation de charges doit pouvoir être comprise et rapprochée des dépenses réellement imputables au locataire. Si le montant vous semble excessif, commencez par demander un décompte détaillé et les justificatifs utiles.",
    points: [
      { title: "Demander le détail des charges", text: "Vérifiez la période concernée, les provisions déjà versées et la ventilation des dépenses. Un montant global sans explication est difficile à contrôler." },
      { title: "Comparer les postes facturés", text: "Certaines dépenses peuvent relever du propriétaire plutôt que du locataire. Identifiez chaque ligne importante et demandez les justificatifs lorsqu'une dépense vous paraît inhabituelle." },
      { title: "Répondre avec un calcul précis", text: "Si vous contestez, indiquez les lignes en cause et le montant que vous estimez incorrect. Un raisonnement chiffré facilite une résolution amiable." },
    ],
    checklist: ["Bail", "Décomptes de charges", "Quittances", "Justificatifs transmis", "Échanges avec le bailleur"],
    faq: [
      { question: "Puis-je demander les justificatifs ?", answer: "Oui, lorsqu'une régularisation est présentée, les éléments permettant de comprendre les dépenses doivent pouvoir être consultés selon les règles applicables." },
      { question: "Dois-je payer avant de contester ?", answer: "La réponse dépend de la nature du montant et du contexte. Évitez de retenir un paiement sans avoir analysé les conséquences juridiques." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "augmentation-loyer-contestation",
    category: "Logement",
    title: "Augmentation de loyer : quand peut-on la contester ?",
    description: "Les vérifications à faire face à une hausse de loyer et les éléments à comparer avec votre bail.",
    intro: "Une hausse de loyer ne peut pas toujours être appliquée librement. Elle dépend notamment du bail, de la date, du mécanisme utilisé et de règles spécifiques pouvant s'appliquer au logement.",
    points: [
      { title: "Relire la clause de révision", text: "Vérifiez si le bail contient une clause permettant une révision et identifiez la date de référence utilisée. Une hausse doit correspondre au mécanisme réellement prévu." },
      { title: "Contrôler le calcul", text: "Comparez l'ancien loyer, l'indice ou la justification invoquée et le nouveau montant. Une erreur de base ou de période peut fausser le résultat." },
      { title: "Réagir par écrit", text: "Si le calcul ou le principe de la hausse paraît incorrect, exposez vos observations de façon factuelle et conservez la réponse du bailleur ou de l'agence." },
    ],
    checklist: ["Bail", "Anciennes quittances", "Notification de hausse", "Calcul communiqué", "Échanges avec le bailleur"],
    faq: [
      { question: "Le propriétaire peut-il augmenter quand il veut ?", answer: "Non. Une augmentation doit reposer sur un fondement prévu par le bail ou par les règles applicables à la situation." },
      { question: "Une hausse rétroactive est-elle toujours possible ?", answer: "Non. Les conditions de prise d'effet et les délais doivent être vérifiés au cas par cas." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "heures-supplementaires-impayees",
    category: "Travail",
    title: "Heures supplémentaires impayées : comment les réclamer ?",
    description: "Comment préparer les preuves et calculer les heures supplémentaires qui n'ont pas été rémunérées.",
    intro: "Un litige sur les heures supplémentaires se prépare avec méthode. Il faut reconstituer les horaires réellement effectués, les comparer avec les bulletins de salaire et conserver les éléments qui permettent d'étayer votre décompte.",
    points: [
      { title: "Reconstituer vos horaires", text: "Utilisez plannings, pointages, agendas, e-mails professionnels ou tout autre élément licite permettant d'établir vos heures de début, de fin et vos pauses." },
      { title: "Comparer avec les bulletins", text: "Vérifiez les heures payées, les majorations et les éventuels repos compensateurs. Repérez les mois où un écart apparaît." },
      { title: "Présenter un décompte lisible", text: "Un tableau par semaine ou par mois facilite l'analyse. Indiquez les heures réalisées, celles déjà rémunérées et la différence réclamée." },
    ],
    checklist: ["Contrat", "Bulletins de salaire", "Plannings", "Pointages ou agendas", "Échanges professionnels utiles"],
    faq: [
      { question: "Un tableau personnel peut-il servir ?", answer: "Oui comme élément de reconstitution, surtout lorsqu'il est précis et cohérent avec d'autres pièces. Il est préférable de le corroborer avec des documents objectifs." },
      { question: "Puis-je réclamer après avoir quitté l'entreprise ?", answer: "Le départ de l'entreprise n'empêche pas automatiquement une réclamation, mais des délais s'appliquent. Il faut agir sans attendre." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "harcelement-travail-preuves",
    category: "Travail",
    title: "Harcèlement au travail : quelles preuves conserver ?",
    description: "Les éléments à réunir lorsqu'un salarié estime subir des comportements répétés dégradant ses conditions de travail.",
    intro: "Une situation de harcèlement doit être décrite avec des faits précis plutôt qu'avec de simples impressions. Dates, messages, changements de comportement professionnel et témoignages permettent de construire une chronologie exploitable.",
    points: [
      { title: "Créer une chronologie factuelle", text: "Notez les événements, dates, personnes présentes, propos ou décisions concernées. Évitez les formulations vagues et distinguez les faits de votre ressenti." },
      { title: "Conserver les échanges accessibles", text: "E-mails, messages, convocations, objectifs et comptes rendus peuvent être utiles s'ils ont été obtenus légitimement et sont directement liés à votre situation." },
      { title: "Identifier les interlocuteurs", text: "Selon le contexte, plusieurs interlocuteurs internes ou externes peuvent intervenir. Préparez un dossier clair avant de signaler la situation." },
    ],
    checklist: ["Chronologie datée", "E-mails et messages utiles", "Comptes rendus", "Évaluations ou sanctions", "Témoignages éventuels"],
    faq: [
      { question: "Dois-je tout enregistrer ?", answer: "Non. La collecte de preuves doit respecter la loi et la confidentialité. Privilégiez les éléments auxquels vous avez légitimement accès." },
      { question: "Un seul incident suffit-il ?", answer: "La qualification dépend de la nature des faits. Certains comportements sont appréciés dans leur répétition, tandis que d'autres situations peuvent relever d'autres protections juridiques." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "solde-de-tout-compte-contestation",
    category: "Travail",
    title: "Solde de tout compte : comment vérifier et contester ?",
    description: "Les sommes à contrôler après la fin d'un contrat de travail et les documents à conserver avant de signer.",
    intro: "À la fin d'un contrat, plusieurs sommes peuvent être dues : salaire restant, congés, primes, indemnités ou régularisations. Il est utile de contrôler le détail avant de considérer le dossier comme définitivement réglé.",
    points: [
      { title: "Comparer avec vos derniers bulletins", text: "Vérifiez les périodes travaillées, les congés restants, les primes et les éventuelles retenues. Reconstituez les montants séparément." },
      { title: "Contrôler les documents de fin de contrat", text: "Assurez-vous que les documents remis correspondent à votre situation et que les dates sont cohérentes avec la rupture du contrat." },
      { title: "Contester précisément les écarts", text: "Indiquez les lignes et montants contestés plutôt qu'une réclamation générale. Joignez les pièces qui permettent de recalculer les sommes." },
    ],
    checklist: ["Derniers bulletins", "Contrat et avenants", "Solde de tout compte", "Compte de congés", "Documents de rupture"],
    faq: [
      { question: "Dois-je signer immédiatement ?", answer: "Vous pouvez demander le temps nécessaire pour vérifier les montants et comprendre les documents qui vous sont remis." },
      { question: "Une erreur peut-elle être corrigée après paiement ?", answer: "Oui dans certaines conditions. Les délais et les effets d'une éventuelle signature doivent être analysés." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "prudhommes-preparer-dossier",
    category: "Travail",
    title: "Conseil de prud'hommes : comment préparer son dossier ?",
    description: "Organiser les faits, les demandes et les preuves avant une démarche devant le conseil de prud'hommes.",
    intro: "Un dossier prud'homal gagne à être simple à lire et chronologique. Avant toute saisine, il faut identifier les demandes exactes, les montants concernés et les documents qui permettent de démontrer chaque point.",
    points: [
      { title: "Établir une chronologie", text: "Présentez l'embauche, les événements importants, les échanges et la rupture éventuelle dans l'ordre. Une chronologie courte aide à comprendre rapidement le litige." },
      { title: "Relier chaque demande à une preuve", text: "Pour chaque salaire, indemnité ou contestation, identifiez les documents qui justifient votre position. Évitez d'accumuler des pièces sans lien clair." },
      { title: "Chiffrer les demandes", text: "Lorsque vous réclamez une somme, préparez un calcul compréhensible. Conservez les hypothèses et justificatifs utilisés." },
    ],
    checklist: ["Contrat", "Bulletins", "Courriers de l'employeur", "Chronologie", "Tableau des demandes chiffrées"],
    faq: [
      { question: "Faut-il un avocat ?", answer: "La représentation par avocat n'est pas systématiquement obligatoire, mais un accompagnement peut être utile selon la complexité et les enjeux du dossier." },
      { question: "Puis-je ajouter des pièces plus tard ?", answer: "Une procédure prévoit des échanges de pièces et d'arguments. Il est néanmoins préférable de préparer un dossier aussi complet que possible dès le départ." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "droit-de-visite-non-respecte",
    category: "Famille",
    title: "Droit de visite non respecté : que faire ?",
    description: "Les démarches à envisager lorsque les modalités de résidence ou de droit de visite fixées pour un enfant ne sont pas respectées.",
    intro: "Les difficultés liées au droit de visite doivent être documentées avec précision. Il faut distinguer un incident ponctuel d'une situation répétée et conserver le jugement ou l'accord qui fixe l'organisation actuelle.",
    points: [
      { title: "Relire la décision applicable", text: "Vérifiez les jours, horaires, lieux de remise de l'enfant et éventuelles modalités particulières. Les termes exacts de la décision sont essentiels." },
      { title: "Documenter les incidents", text: "Notez les dates, retards, annulations et échanges. Conservez les messages afin de montrer la répétition éventuelle des difficultés." },
      { title: "Chercher une solution adaptée", text: "Selon la gravité, une clarification amiable, une médiation ou une nouvelle demande au juge peuvent être envisagées." },
    ],
    checklist: ["Jugement ou convention", "Calendrier des incidents", "Messages échangés", "Justificatifs de déplacements", "Éventuelles plaintes ou mains courantes"],
    faq: [
      { question: "Un retard isolé justifie-t-il une procédure ?", answer: "Un incident isolé n'a pas la même portée qu'une répétition. Il faut apprécier sa gravité et son contexte." },
      { question: "Puis-je modifier seul les modalités ?", answer: "En principe, une organisation fixée par décision ou convention ne doit pas être modifiée unilatéralement de façon durable sans accord ou nouvelle décision." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "revision-pension-alimentaire",
    category: "Famille",
    title: "Révision de pension alimentaire : quand la demander ?",
    description: "Les éléments à préparer lorsqu'un changement de revenus, de charges ou de besoins peut justifier une révision.",
    intro: "Le montant d'une pension peut devenir inadapté lorsque la situation financière des parents ou les besoins de l'enfant évoluent de manière significative. Une demande sérieuse doit reposer sur des éléments actuels et vérifiables.",
    points: [
      { title: "Comparer l'ancienne et la nouvelle situation", text: "Revenus, charges, logement, frais liés aux enfants et changements professionnels doivent être présentés de façon claire." },
      { title: "Rassembler les justificatifs récents", text: "Préparez avis d'imposition, bulletins, allocations, loyers, crédits et dépenses importantes concernant l'enfant." },
      { title: "Éviter les modifications unilatérales", text: "Tant qu'un nouveau montant n'a pas été convenu ou fixé, la pension existante continue en principe de produire ses effets." },
    ],
    checklist: ["Décision actuelle", "Revenus récents", "Charges", "Dépenses pour l'enfant", "Justificatifs du changement invoqué"],
    faq: [
      { question: "Une baisse de salaire suffit-elle ?", answer: "Elle peut être prise en compte si elle est réelle et suffisamment significative, mais l'ensemble de la situation est généralement examiné." },
      { question: "Puis-je demander une hausse ?", answer: "Oui lorsqu'une évolution des besoins ou des ressources peut justifier une réévaluation." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "divorce-separation-documents",
    category: "Famille",
    title: "Divorce ou séparation : quels documents préparer ?",
    description: "La liste des informations et documents utiles pour organiser une séparation et anticiper les questions familiales et financières.",
    intro: "Une séparation implique souvent plusieurs sujets en même temps : logement, enfants, comptes, crédits, patrimoine et dépenses courantes. Préparer les documents en amont permet d'obtenir une vision claire avant de prendre des décisions importantes.",
    points: [
      { title: "Lister les éléments familiaux", text: "Identifiez l'organisation actuelle des enfants, les dépenses, les emplois du temps et les éventuels accords déjà trouvés." },
      { title: "Recenser les éléments financiers", text: "Revenus, comptes, crédits, loyers, biens et charges doivent être regroupés afin de mesurer les conséquences concrètes de la séparation." },
      { title: "Conserver les accords par écrit", text: "Même lorsqu'un échange reste amiable, formaliser les points d'accord limite les incompréhensions et facilite les étapes suivantes." },
    ],
    checklist: ["Pièces d'identité", "Livret de famille", "Revenus et avis d'imposition", "Crédits et comptes", "Documents relatifs aux enfants"],
    faq: [
      { question: "Faut-il tout régler avant de se séparer ?", answer: "Non, mais il est utile d'identifier rapidement les urgences : logement, enfants, dépenses et accès aux documents." },
      { question: "Puis-je préparer le dossier avant de consulter ?", answer: "Oui. Un dossier organisé permet généralement d'obtenir une analyse plus rapide et plus précise." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "achat-internet-non-livre",
    category: "Consommation",
    title: "Achat internet non livré : quels recours ?",
    description: "Que faire lorsqu'une commande en ligne n'arrive pas, arrive très en retard ou que le vendeur ne répond plus.",
    intro: "Un litige de livraison se traite d'abord avec les preuves de commande et de paiement. Il faut identifier la date annoncée, l'état du suivi et les réponses du vendeur avant d'engager une réclamation plus formelle.",
    points: [
      { title: "Rassembler la preuve de commande", text: "Conservez confirmation, facture, conditions de vente, capture de la date de livraison annoncée et preuve du paiement." },
      { title: "Demander une solution écrite", text: "Contactez le vendeur avec une demande claire : livraison, nouvelle date ou remboursement selon la situation. Conservez chaque réponse." },
      { title: "Escalader si nécessaire", text: "Si le vendeur ne répond pas, une mise en demeure, un dispositif de médiation ou d'autres voies de recours peuvent être envisagés selon le dossier." },
    ],
    checklist: ["Confirmation de commande", "Facture", "Preuve de paiement", "Suivi de livraison", "Échanges avec le vendeur"],
    faq: [
      { question: "Le transporteur est-il toujours responsable ?", answer: "Votre interlocuteur contractuel reste souvent le vendeur, même lorsqu'un transporteur intervient. Il faut examiner les circonstances précises de la livraison." },
      { question: "Puis-je demander un remboursement ?", answer: "Selon le retard, les engagements du vendeur et les démarches déjà effectuées, un remboursement peut être envisagé." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "produit-defectueux-garantie",
    category: "Consommation",
    title: "Produit défectueux : garantie, réparation ou remboursement ?",
    description: "Les premières démarches lorsqu'un produit tombe en panne, présente un défaut ou ne correspond pas à ce qui était annoncé.",
    intro: "Face à un produit défectueux, il faut d'abord identifier la date d'achat, le vendeur, la nature du défaut et les garanties applicables. Une preuve claire du problème facilite la prise en charge.",
    points: [
      { title: "Identifier précisément le défaut", text: "Décrivez quand le problème apparaît, ce qui ne fonctionne plus et si le défaut était visible dès la livraison. Photos ou vidéos peuvent compléter la preuve." },
      { title: "Conserver la preuve d'achat", text: "Facture, ticket, confirmation de commande ou relevé permettent d'établir la date et le vendeur concerné." },
      { title: "Formuler la demande adaptée", text: "Réparation, remplacement, réduction du prix ou remboursement peuvent dépendre du régime applicable et de la situation concrète." },
    ],
    checklist: ["Facture ou ticket", "Photos du défaut", "Notice ou référence du produit", "Échanges SAV", "Conditions de garantie"],
    faq: [
      { question: "Le fabricant est-il mon seul interlocuteur ?", answer: "Pas nécessairement. Selon la garantie invoquée, le vendeur peut rester un interlocuteur central." },
      { question: "Une garantie commerciale remplace-t-elle les garanties légales ?", answer: "Non. Une garantie commerciale peut s'ajouter à d'autres protections sans nécessairement les remplacer." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "resiliation-abonnement-litige",
    category: "Consommation",
    title: "Résiliation d'abonnement refusée : que faire ?",
    description: "Les réflexes à avoir lorsqu'un opérateur, une salle, une plateforme ou un autre professionnel continue de facturer après une demande de résiliation.",
    intro: "Un litige de résiliation dépend du contrat, de la durée d'engagement et de la manière dont la demande a été envoyée. Avant de contester les prélèvements, vérifiez les dates et conservez la preuve de votre démarche.",
    points: [
      { title: "Relire les conditions de résiliation", text: "Identifiez durée d'engagement, préavis, motif éventuel et mode de notification. Comparez ces règles avec la demande que vous avez réellement envoyée." },
      { title: "Prouver la date de votre demande", text: "Accusé, e-mail, espace client ou courrier permettent d'établir la date à partir de laquelle la résiliation devait être traitée." },
      { title: "Contester les factures concernées", text: "Listez les prélèvements effectués après la date contestée et demandez une régularisation chiffrée." },
    ],
    checklist: ["Contrat", "Conditions générales", "Preuve de résiliation", "Factures", "Relevés bancaires"],
    faq: [
      { question: "Puis-je bloquer les prélèvements ?", answer: "Un blocage bancaire ne règle pas automatiquement le litige contractuel. Vérifiez d'abord les conséquences et formalisez votre contestation." },
      { question: "Une résiliation par espace client est-elle valable ?", answer: "Cela dépend du service et du dispositif proposé. Conservez toute confirmation affichée ou envoyée par e-mail." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "mise-en-demeure-facture-impayee",
    category: "Entreprise",
    title: "Facture impayée : comment rédiger une mise en demeure ?",
    description: "Les informations à vérifier avant d'adresser une mise en demeure à un client professionnel ou particulier.",
    intro: "Une mise en demeure efficace doit permettre au débiteur de comprendre immédiatement l'origine de la dette, son montant et ce qui est attendu. Avant l'envoi, vérifiez que la facture est exigible et que les prestations ont bien été documentées.",
    points: [
      { title: "Vérifier la créance", text: "Contrat, devis, bon de commande, preuve de livraison ou d'exécution et facture doivent être cohérents. Repérez tout désaccord déjà exprimé par le client." },
      { title: "Présenter un décompte clair", text: "Indiquez le principal, les éventuels paiements déjà reçus et les accessoires réclamés lorsqu'ils sont applicables." },
      { title: "Fixer une demande précise", text: "La lettre doit identifier la facture, rappeler les relances et demander le règlement dans un délai clairement indiqué." },
    ],
    checklist: ["Devis ou contrat", "Facture", "Preuve d'exécution", "Relances", "Décompte actualisé"],
    faq: [
      { question: "Une relance suffit-elle ?", answer: "Une relance amiable peut suffire si le retard est ponctuel. La mise en demeure formalise davantage la demande lorsqu'aucune solution n'est trouvée." },
      { question: "Puis-je réclamer des pénalités ?", answer: "Cela dépend du contrat, du type de client et des règles applicables. Vérifiez les mentions contractuelles et légales avant de les ajouter." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "litige-fournisseur-entreprise",
    category: "Entreprise",
    title: "Litige avec un fournisseur : comment protéger son entreprise ?",
    description: "Retard, mauvaise qualité, facture contestée : organiser les preuves et les demandes face à un fournisseur professionnel.",
    intro: "Un litige fournisseur peut rapidement perturber l'activité. Il est important d'identifier ce qui était prévu au contrat, ce qui a réellement été livré ou exécuté et les conséquences financières du manquement.",
    points: [
      { title: "Relire les engagements contractuels", text: "Délais, quantité, qualité, prix, pénalités et procédure de réclamation doivent être comparés aux faits réels." },
      { title: "Documenter le manquement", text: "Photos, réserves, bons de livraison, e-mails et constats permettent d'établir le retard, le défaut ou la non-conformité." },
      { title: "Chiffrer votre demande", text: "Distinguez remboursement, avoir, remplacement, dommages éventuels et factures contestées. Un chiffrage précis facilite la négociation." },
    ],
    checklist: ["Contrat ou CGV", "Bons de commande", "Factures", "Preuves de non-conformité", "Échanges avec le fournisseur"],
    faq: [
      { question: "Puis-je suspendre le paiement ?", answer: "La suspension d'un paiement peut avoir des conséquences. Elle doit être analysée au regard du contrat et de la gravité du manquement." },
      { question: "Faut-il mettre fin au contrat immédiatement ?", answer: "Pas nécessairement. Une résiliation doit respecter les clauses contractuelles et le contexte du litige." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "contester-amende",
    category: "Administration",
    title: "Contester une amende : quelles étapes suivre ?",
    description: "Les vérifications et pièces à préparer avant de contester une amende ou un avis de contravention.",
    intro: "Une contestation d'amende doit respecter le motif, la procédure et les délais indiqués sur l'avis reçu. Avant d'agir, relisez précisément le document et rassemblez les preuves correspondant au motif invoqué.",
    points: [
      { title: "Identifier le type d'avis", text: "La procédure peut varier selon l'infraction, le mode de constatation et le stade du dossier. Utilisez les références figurant sur l'avis pour éviter une démarche inadaptée." },
      { title: "Préparer un motif précis", text: "Expliquez les faits de manière chronologique et joignez uniquement les pièces directement utiles : cession, vol, erreur d'immatriculation, justificatifs de lieu ou autre élément pertinent." },
      { title: "Respecter la procédure indiquée", text: "Suivez le canal et les délais prévus. Conservez une preuve complète de la contestation et de toutes les pièces transmises." },
    ],
    checklist: ["Avis reçu", "Référence du dossier", "Justificatifs du motif", "Copie de la contestation", "Preuve d'envoi"],
    faq: [
      { question: "Dois-je payer avant de contester ?", answer: "Selon la procédure, paiement et consignation peuvent produire des effets différents. Suivez exactement les indications correspondant à votre avis." },
      { question: "Puis-je contester en ligne ?", answer: "Certaines procédures le permettent. Vérifiez le canal officiel indiqué sur l'avis ou le site de l'administration concernée." },
    ],
    updatedAt: "2026-08-07",
  },
  {
    slug: "recours-decision-administrative",
    category: "Administration",
    title: "Contester une décision administrative : recours gracieux ou contentieux ?",
    description: "Comprendre les premiers recours lorsqu'une administration refuse une demande, retire un droit ou prend une décision défavorable.",
    intro: "Une décision administrative doit être analysée dès sa réception car des délais de recours peuvent commencer à courir. Il faut identifier l'autorité qui a pris la décision, ses motifs et les voies de recours mentionnées.",
    points: [
      { title: "Lire la décision en entier", text: "Repérez la date, l'autorité, les motifs, les références utilisées et les indications relatives aux recours. Ces éléments orientent la suite." },
      { title: "Choisir le recours adapté", text: "Selon le dossier, un recours gracieux, hiérarchique ou contentieux peut être envisagé. Le bon choix dépend de l'objectif et du délai disponible." },
      { title: "Argumenter avec des pièces", text: "Répondez aux motifs de la décision et joignez les documents qui démontrent l'erreur, l'élément nouveau ou la situation que l'administration n'a pas correctement appréciée." },
    ],
    checklist: ["Décision administrative", "Preuve de réception", "Dossier initial", "Pièces nouvelles", "Chronologie des échanges"],
    faq: [
      { question: "Un recours gracieux suspend-il toujours le délai ?", answer: "Les effets d'un recours sur les délais dépendent de la procédure concernée. Il faut vérifier le régime applicable avant d'attendre une réponse." },
      { question: "Puis-je demander les motifs ?", answer: "Selon la nature de la décision et les informations déjà fournies, des possibilités existent pour obtenir ou compléter la motivation." },
    ],
    updatedAt: "2026-08-07",
  },
];
