import Link from "next/link";
import "./home.css";

const domains = [
  ["⌂", "Logement", "Bail, dépôt de garantie, travaux, expulsion et voisinage."],
  ["◇", "Travail", "Contrat, salaire, sanction, licenciement et rupture conventionnelle."],
  ["◎", "Consommation", "Achat, remboursement, abonnement, banque et assurance."],
  ["♙", "Famille", "Séparation, pension, autorité parentale et démarches amiables."],
  ["▦", "Entreprise", "Contrats, impayés, litiges commerciaux et relations fournisseurs."],
  ["⌖", "Administration", "Décision administrative, recours, contestation et formalités."],
];

export default function HomePage() {
  return <main className="public-site">
    <div className="announcement"><span>Assistance juridique en ligne pour particuliers et professionnels</span><Link href="/impayes">Nouveau : LEXIA Impayés →</Link></div>
    <header className="public-header"><div className="public-container public-nav"><Link href="/" className="public-logo">LEXIA<span>.</span></Link><nav className="public-links"><Link href="#fonctionnement">Fonctionnement</Link><Link href="#domaines">Domaines</Link><Link href="/impayes">Impayés</Link><Link href="/conseils-juridiques">Guides</Link><Link href="#tarifs">Tarifs</Link></nav><div className="public-actions"><Link className="public-login" href="/connexion">Se connecter</Link><Link className="public-button public-button-dark" href="/inscription">Créer mon espace</Link></div></div></header>
    <section className="public-hero"><div className="public-container hero-layout"><div className="hero-copy"><div className="hero-label"><span>●</span> Assistance humaine et confidentielle</div><h1>Le juridique devient enfin <em>plus simple.</em></h1><p>Décrivez votre situation, transmettez vos documents et échangez avec un professionnel depuis un espace sécurisé. LEXIA vous aide à comprendre, agir et rédiger les bonnes démarches.</p><div className="hero-buttons"><Link className="public-button public-button-gold" href="/inscription">Déposer ma demande</Link><Link className="public-button public-button-light" href="/impayes">J’ai un impayé</Link></div><div className="hero-proof"><div><strong>13 €</strong><span>Ouverture particulier</span></div><div><strong>29 €</strong><span>Ouverture professionnel</span></div><div><strong>100 %</strong><span>Espace confidentiel</span></div></div></div><div className="product-preview" aria-label="Aperçu LEXIA"><div className="preview-top"><div className="preview-brand">LEXIA<span>.</span></div><div className="preview-user">✓</div></div><div className="preview-content" style={{padding:28}}><small>ESPACE SÉCURISÉ</small><h2>Votre dossier centralisé</h2><div className="preview-banner"><div><span>DOSSIER EN COURS</span><strong>Analyse et démarches</strong><p>Documents, messages et suivi réunis au même endroit.</p></div></div><div className="preview-stats"><article><span>Suivi</span><strong>24/7</strong></article><article><span>Espace</span><strong>Privé</strong></article></div></div></div></div></section>
    <section className="trust-strip" id="confiance"><div className="public-container trust-items"><div><span>01</span><p><strong>Accompagnement humain</strong>Des réponses adaptées à votre situation.</p></div><div><span>02</span><p><strong>Documents centralisés</strong>Toutes vos pièces dans un espace unique.</p></div><div><span>03</span><p><strong>Résolution amiable</strong>Des démarches structurées lorsque cela est possible.</p></div><div><span>04</span><p><strong>Relais professionnel</strong>Orientation lorsque nécessaire.</p></div></div></section>
    <section className="public-section process-section" id="fonctionnement"><div className="public-container"><div className="section-heading centered"><span>UN PARCOURS SIMPLE</span><h2>Votre demande prise en charge en quelques étapes.</h2><p>LEXIA rassemble les informations, documents et échanges nécessaires pour faire avancer votre situation.</p></div><div className="process-grid"><article><div className="process-number">01</div><h3>Expliquez</h3><p>Décrivez les faits et votre objectif.</p></article><article><div className="process-number">02</div><h3>Documentez</h3><p>Ajoutez contrats, courriers et justificatifs.</p></article><article><div className="process-number">03</div><h3>Échangez</h3><p>Suivez votre dossier depuis la messagerie sécurisée.</p></article><article><div className="process-number">04</div><h3>Agissez</h3><p>Recevez les prochaines démarches adaptées.</p></article></div></div></section>
    <section className="public-section domains-section" id="domaines"><div className="public-container domains-layout"><div className="section-heading left"><span>DOMAINES D’INTERVENTION</span><h2>Une première assistance pour les situations du quotidien.</h2><p>Particulier ou professionnel, sélectionnez le motif correspondant à votre situation.</p><Link href="/impayes" className="text-link">Découvrir LEXIA Impayés →</Link></div><div className="domain-grid">{domains.map(([icon,title,description])=><article key={title}><div>{icon}</div><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
    <section className="public-section pricing-section" id="tarifs"><div className="public-container"><div className="section-heading centered light-heading"><span>TARIFICATION CLAIRE</span><h2>Un coût connu dès le départ.</h2><p>Toute prestation complémentaire doit être présentée et acceptée avant paiement.</p></div><div className="pricing-grid"><article className="price-card"><div className="price-card-top"><span>PARTICULIER</span><div><strong>13 €</strong><small>TTC / dossier</small></div></div><p>Pour les litiges et démarches de la vie quotidienne.</p><Link href="/inscription" className="public-button public-button-gold">Commencer</Link></article><article className="price-card featured-price"><div className="popular-tag">PROFESSIONNELS</div><div className="price-card-top"><span>ENTREPRISE</span><div><strong>29 €</strong><small>TTC / dossier</small></div></div><p>Pour les sociétés, indépendants et associations.</p><Link href="/impayes" className="public-button public-button-light">Service Impayés</Link></article></div></div></section>
    <section className="public-section final-cta"><div className="public-container final-card"><div><span>VOTRE ESPACE JURIDIQUE</span><h2>Une situation vous préoccupe ? Commencez par nous l’expliquer.</h2><p>Créez votre compte, transmettez les informations utiles et suivez votre dossier en ligne.</p></div><div className="final-actions"><Link href="/inscription" className="public-button public-button-gold">Créer mon dossier</Link><Link href="/impayes" className="final-login">Déclarer un impayé →</Link></div></div></section>
    <footer className="public-footer"><div className="public-container footer-main"><div><Link href="/" className="footer-logo">LEXIA<span>.</span></Link><p>L’assistance juridique en ligne, simple, humaine et sécurisée.</p></div><div><b>Services</b><Link href="/impayes">LEXIA Impayés</Link><Link href="/conseils-juridiques">Conseils juridiques</Link></div><div><b>Mon espace</b><Link href="/inscription">Créer un compte</Link><Link href="/connexion">Se connecter</Link><Link href="/nouveau-dossier">Déposer un dossier</Link></div><div><b>Informations</b><Link href="/confidentialite">Confidentialité</Link><Link href="/conditions">Conditions générales</Link><Link href="/mentions-legales">Mentions légales</Link></div></div><div className="public-container footer-bottom"><span>© 2026 LEXIA. Tous droits réservés.</span></div></footer>
  </main>;
}
